name: Ecotropolis
main: us.danielpmc.ecotropolis.Ecotropolis
version: 3.0
author: danielpmc

commands:
   heal:
      description: Heal yourself!
      usage: /heal
   efly:
      description: Enable Fly!
      usage: /efly
   dfly:
      description: Disable Fly!
      usage: /dfly
   feed:
      description: Feed yourself!
      usage: /feed
   gmc:
      description: Gamemode creative
      usage: /gmc
   gms:
      description: Gamemode survival
      usage: /gms
   tp:
      description: teleport to a player!
      usage: /tp
   discord:
      description: link to our discord
      usage: /discord
   website:
      description: link to our website
      usage: /website
   ecoabout:
      description: Info about plugin
      usage: /ecoabout
   etps:
      description: Gets the current ticks per second for the server!
      usage: /etps
   eban:
      description: BAN BAN BANNNNNNNNNNNN!
   eunban:
      description: oh meh god unban??
   ereload:
      description: Reloads the plugin!
      usage: /ereload

permissions:
   ecotropolis.ecoabout:
      description: Allows you to use /ecoabout
      default: true
   ecotropolis.tps:
      description: Allows you to use /etps
      default: true
   ecotropolis.heal:
      description: Allows you to use /heal
      default: op
   ecotropolis.efly:
      description: Allows you to use /efly
      default: op
   ecotropolis.efly.others:
      description: Allows you to use /efly on others
      default: op
   ecotropolis.dfly:
      description: Allows you to use /dfly
      default: op
   ecotropolis.dfly.others:
      description: Allows you to use /dfly on others
      default: op
   ecotropolis.feed:
      description: Allows you to use /feed
      default: op
   ecotropolis.gmc:
      description: Allows you to use /gmc
      default: op
   ecotropolis.gmc.others:
      description: Allows you to use /gmc on others
      default: op
   ecotropolis.gms:
      description: Allows you to use /gms
      default: op
   ecotropolis.gms.others:
      description: Allows you to use /gms on others
      default: op
   ecotropolis.tp:
      description: Allows you to use /tp
      default: op
   ecotropolis.discord:
      description: Allows you to use /discord
      default: true
   ecotropolis.website:
      description: Allows you to use /website
      default: true
   ecotropolis.ereload:
      description: Allows you to use /ereload
      default: op
   ecotropolis.eban:
     description: Allows you to use /eban
     default: op
   ecotropolis.eunban:
      description: Allows you to use /eunban
      default: op